on: push

defaults:
  run:
    shell: bash

jobs:
  rando-title:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
      
    steps: 
      - uses: actions/checkout@v2
      - run: bash
      - run: sudo apt install hugo
      - run: ls
      - run: pwd
      - run: hugo  
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./public
      - uses: actions/deploy-pages@v4
